# Name：楊淯元
# ID：B05603043
# Subject：Phone
# Date: 4/20, 2017

---
title: "HW06_B05603043_Phone"
output: pdf_document
---
##  1.Phone code
將資料一一輸入Brand, Model, Price, Screen, Weight, GB, Data

```{r Data, echo=TRUE}
Brand <- c("Apple", "HTC", "HTC", "ASUS", "ASUS")
Model <- c("iPhone7", "OneM8", "OneS9", "ZenFoneDeluxe", "ZenFoneZoom")
Price <- c(24500, 21900, 9990, 8990, 15990)
Screen <- c("4.7", "5", "5", "5.5", "5.5")
Weight <- c(138, 160, 158, 170, 185)
GB <- c(32, 16, 32, 16, 64)
Data <- c(20160916, 20140328, 20160617, 20150827, 20151201)
```
Number：製作矩陣，輸入資料Price, Screen, Weight，3行，5列，沿著「行」排列

```{r Number, echo=TRUE}
Number <- matrix(c(Price, Screen, Weight), nrow=5, ncol=3, byrow=FALSE)
Number
```

##  2.Phone & PhoneCheap

Phone：將Brand, Model, Price, Screen, Weight, GB, Data七組資料放入Phone資料框

PhoneCheap：利用Phone的欄位Price判定資料內容是否<=10000，並將符合者放入PhoneCheap
```{r Phone&PhoneCheap, echo=TRUE}
Phone <- data.frame(Brand, Model, Price, Screen, Weight, GB, Data)
Phone
PhoneCheap <- Phone[Phone$Price<=10000, ]
PhoneCheap
```
